In [1]:
#input: smoothed openpose joint positions for one episode
#40 frames as input

#change z points to zeros
#flip rows and columns
#center data

import pandas as pd
import numpy as np
import cv2
import csv
import sys
import os


def toSpatio(dir_path, filename):
    frames = 40
    df = pd.read_csv(dir_path + filename, header=None)
    arr1 = df.to_numpy()

    print(arr1)

    #print(arr1)

    #insert zeros into every 3rd column
    j = range(2, 51, 2)
    k = 0 #[0] * frames
    raw_data = np.insert(arr1, j, k, axis = 1)
    raw_data_1 = raw_data.reshape(75 * frames)
    raw_data_2 = raw_data_1.reshape(75, frames, order = 'F')
    #arr1[:, range(2, len(arr1 + 1), 3)] = 0

    print(raw_data_2)

    #center data
    
    data_mean = np.tile(np.mean(raw_data_2, axis=1, keepdims=True), (1, raw_data_2.shape[1]))
    centered_data = raw_data_2 - data_mean
    scaling_value = np.ceil(max(np.max(centered_data), abs(np.min(centered_data))))
    data_correct = centered_data / scaling_value
    

    #write to csv
    filename = filename[:-4]
    f = open(dir_path + filename + "_smoothed.csv", 'w', newline = '')
    w = csv.writer(f)
    np.apply_along_axis(w.writerow, axis = 1, arr = data_correct)
    f.close()



In [2]:
#rerun all of the squats with new centering
dir_path = r'C:\Users\Molly Meadows\OneDrive - University of Idaho\Documents\2023-2024\Capstone Project\26-Physical-Rehabilitation\LungeAndShoulderSegmentedVideos\InLungeTest\same_size_csvs\\'

squat = []

for path in os.listdir(dir_path):
    # check if current path is a file
    if os.path.isfile(os.path.join(dir_path, path)):
        squat.append(path)
        
for f in squat:
    toSpatio(dir_path, f)
    #print(f)


[[45.   21.   49.   ... 84.   37.   83.  ]
 [44.26 21.   48.26 ... 84.74 37.   83.  ]
 [43.94 21.   47.94 ... 85.   37.   83.  ]
 ...
 [44.   19.   49.   ... 83.   37.   83.  ]
 [44.   19.   49.   ... 82.88 37.   83.  ]
 [44.   19.   49.   ... 79.46 37.   83.  ]]
[[45.   44.26 43.94 ... 44.   44.   44.  ]
 [21.   21.   21.   ... 19.   19.   19.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 ...
 [37.   37.   37.   ... 37.   37.   37.  ]
 [83.   83.   83.   ... 83.   83.   83.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]]
[[44.     19.     49.     ... 77.     37.     83.    ]
 [44.     19.     49.     ... 78.6    36.0725 83.    ]
 [44.     19.     49.     ... 82.54   36.055  83.    ]
 ...
 [41.9175 20.     47.24   ... 81.0825 35.     82.    ]
 [42.46   20.045  48.     ... 81.045  35.     82.    ]
 [43.     20.9725 48.     ... 73.425  35.     82.    ]]
[[44.     44.     44.     ... 41.9175 42.46   43.    ]
 [19.     19.     19.     ... 20.     20.045  20.9725]
 [ 0.      0.      0.     

[[38.    20.    35.9   ... 82.    20.    78.8  ]
 [36.54  20.    35.    ... 82.    20.    78.485]
 [35.91  20.    34.91  ... 82.09  20.    78.09 ]
 ...
 [39.38  22.38  38.035 ... 84.    20.655 80.965]
 [38.08  22.    37.09  ... 84.    20.26  80.09 ]
 [37.045 21.46  36.46  ... 84.    20.1   80.   ]]
[[38.    36.54  35.91  ... 39.38  38.08  37.045]
 [20.    20.    20.    ... 22.38  22.    21.46 ]
 [ 0.     0.     0.    ...  0.     0.     0.   ]
 ...
 [20.    20.    20.    ... 20.655 20.26  20.1  ]
 [78.8   78.485 78.09  ... 80.965 80.09  80.   ]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
[[36.1   21.    36.    ... 84.    21.    80.   ]
 [36.    21.    36.    ... 84.    20.085 80.   ]
 [36.    21.    36.    ... 84.    20.    80.   ]
 ...
 [46.405 26.045 42.99  ... 85.54  22.    81.   ]
 [44.37  25.93  41.96  ... 85.41  22.    81.66 ]
 [43.22  25.015 42.445 ... 85.985 22.    82.   ]]
[[36.1   36.    36.    ... 46.405 44.37  43.22 ]
 [21.    21.    21.    ... 26.045 25.93  25.015]
 [

In [27]:
toSpatio("C:/Users/Molly Meadows/OneDrive - University of Idaho/Documents/2023-2024/Capstone Project/Retest of videos/same_size_csvs/", "MollyGoodSquat.csv")

[[38.   28.   38.   ... 82.   33.   79.  ]
 [38.   28.66 38.   ... 82.   33.   79.66]
 [38.   29.   38.   ... 82.   33.   79.96]
 ...
 [38.82 31.18 38.   ... 83.   33.   81.  ]
 [39.   30.42 38.   ... 83.   33.   81.  ]
 [39.   30.   38.   ... 83.   33.   81.  ]]
[[38.   38.   38.   ... 38.82 39.   39.  ]
 [28.   28.66 29.   ... 31.18 30.42 30.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 ...
 [33.   33.   33.   ... 33.   33.   33.  ]
 [79.   79.66 79.96 ... 81.   81.   81.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]]


In [8]:
if __name__ == "__main__":
    # Check if both input and output directories are provided as command-line arguments
    if len(sys.argv) != 2:
        print("Usage:  <input_CSV> ")
        exit(1)

    input_csv = sys.argv[1]
    input_video = os.path.abspath(sys.argv[1])
    print(input_video)
    
    toSpatio(input_csv)

Usage:  <input_CSV> 
C:\Users\Molly Meadows\OneDrive - University of Idaho\Documents\2023-2024\Capstone Project\26-Physical-Rehabilitation\Retest of videos\PreProcessingScripts\-f


FileNotFoundError: [Errno 2] No such file or directory: '-f.csv'